// ISO 3166-1 Country list (French names)
export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  {code: 'AF', name: 'Afghanistan'},
  {code: 'ZA', name: 'Afrique du Sud'},
  {code: 'AL', name: 'Albanie'},
  {code: 'DZ', name: 'Algerie'},
  {code: 'DE', name: 'Allemagne'},
  {code: 'AD', name: 'Andorre'},
  {code: 'AO', name: 'Angola'},
  {code: 'SA', name: 'Arabie Saoudite'},
  {code: 'AR', name: 'Argentine'},
  {code: 'AM', name: 'Armenie'},
  {code: 'AU', name: 'Australie'},
  {code: 'AT', name: 'Autriche'},
  {code: 'AZ', name: 'Azerbaidjan'},
  {code: 'BH', name: 'Bahrein'},
  {code: 'BD', name: 'Bangladesh'},
  {code: 'BE', name: 'Belgique'},
  {code: 'BJ', name: 'Benin'},
  {code: 'BT', name: 'Bhoutan'},
  {code: 'BY', name: 'Bielorussie'},
  {code: 'MM', name: 'Birmanie'},
  {code: 'BO', name: 'Bolivie'},
  {code: 'BA', name: 'Bosnie-Herzegovine'},
  {code: 'BW', name: 'Botswana'},
  {code: 'BR', name: 'Bresil'},
  {code: 'BN', name: 'Brunei'},
  {code: 'BG', name: 'Bulgarie'},
  {code: 'BF', name: 'Burkina Faso'},
  {code: 'BI', name: 'Burundi'},
  {code: 'KH', name: 'Cambodge'},
  {code: 'CM', name: 'Cameroun'},
  {code: 'CA', name: 'Canada'},
  {code: 'CV', name: 'Cap-Vert'},
  {code: 'CF', name: 'Centrafrique'},
  {code: 'CL', name: 'Chili'},
  {code: 'CN', name: 'Chine'},
  {code: 'CY', name: 'Chypre'},
  {code: 'CO', name: 'Colombie'},
  {code: 'KM', name: 'Comores'},
  {code: 'CG', name: 'Congo'},
  {code: 'CD', name: 'Congo (RDC)'},
  {code: 'KR', name: 'Coree du Sud'},
  {code: 'KP', name: 'Coree du Nord'},
  {code: 'CR', name: 'Costa Rica'},
  {code: 'CI', name: 'Cote d\'Ivoire'},
  {code: 'HR', name: 'Croatie'},
  {code: 'CU', name: 'Cuba'},
  {code: 'DK', name: 'Danemark'},
  {code: 'DJ', name: 'Djibouti'},
  {code: 'EG', name: 'Egypte'},
  {code: 'AE', name: 'Emirats Arabes Unis'},
  {code: 'EC', name: 'Equateur'},
  {code: 'ER', name: 'Erythree'},
  {code: 'ES', name: 'Espagne'},
  {code: 'EE', name: 'Estonie'},
  {code: 'SZ', name: 'Eswatini'},
  {code: 'US', name: 'Etats-Unis'},
  {code: 'ET', name: 'Ethiopie'},
  {code: 'FI', name: 'Finlande'},
  {code: 'FR', name: 'France'},
  {code: 'GA', name: 'Gabon'},
  {code: 'GM', name: 'Gambie'},
  {code: 'GE', name: 'Georgie'},
  {code: 'GH', name: 'Ghana'},
  {code: 'GR', name: 'Grece'},
  {code: 'GT', name: 'Guatemala'},
  {code: 'GN', name: 'Guinee'},
  {code: 'GQ', name: 'Guinee Equatoriale'},
  {code: 'GW', name: 'Guinee-Bissau'},
  {code: 'GY', name: 'Guyana'},
  {code: 'HT', name: 'Haiti'},
  {code: 'HN', name: 'Honduras'},
  {code: 'HK', name: 'Hong Kong'},
  {code: 'HU', name: 'Hongrie'},
  {code: 'IN', name: 'Inde'},
  {code: 'ID', name: 'Indonesie'},
  {code: 'IQ', name: 'Irak'},
  {code: 'IR', name: 'Iran'},
  {code: 'IE', name: 'Irlande'},
  {code: 'IS', name: 'Islande'},
  {code: 'IL', name: 'Israel'},
  {code: 'IT', name: 'Italie'},
  {code: 'JM', name: 'Jamaique'},
  {code: 'JP', name: 'Japon'},
  {code: 'JO', name: 'Jordanie'},
  {code: 'KZ', name: 'Kazakhstan'},
  {code: 'KE', name: 'Kenya'},
  {code: 'KG', name: 'Kirghizistan'},
  {code: 'KW', name: 'Koweit'},
  {code: 'LA', name: 'Laos'},
  {code: 'LS', name: 'Lesotho'},
  {code: 'LV', name: 'Lettonie'},
  {code: 'LB', name: 'Liban'},
  {code: 'LR', name: 'Liberia'},
  {code: 'LY', name: 'Libye'},
  {code: 'LI', name: 'Liechtenstein'},
  {code: 'LT', name: 'Lituanie'},
  {code: 'LU', name: 'Luxembourg'},
  {code: 'MK', name: 'Macedoine du Nord'},
  {code: 'MG', name: 'Madagascar'},
  {code: 'MY', name: 'Malaisie'},
  {code: 'MW', name: 'Malawi'},
  {code: 'MV', name: 'Maldives'},
  {code: 'ML', name: 'Mali'},
  {code: 'MT', name: 'Malte'},
  {code: 'MA', name: 'Maroc'},
  {code: 'MU', name: 'Maurice'},
  {code: 'MR', name: 'Mauritanie'},
  {code: 'MX', name: 'Mexique'},
  {code: 'MD', name: 'Moldavie'},
  {code: 'MC', name: 'Monaco'},
  {code: 'MN', name: 'Mongolie'},
  {code: 'ME', name: 'Montenegro'},
  {code: 'MZ', name: 'Mozambique'},
  {code: 'NA', name: 'Namibie'},
  {code: 'NP', name: 'Nepal'},
  {code: 'NI', name: 'Nicaragua'},
  {code: 'NE', name: 'Niger'},
  {code: 'NG', name: 'Nigeria'},
  {code: 'NO', name: 'Norvege'},
  {code: 'NZ', name: 'Nouvelle-Zelande'},
  {code: 'OM', name: 'Oman'},
  {code: 'UG', name: 'Ouganda'},
  {code: 'UZ', name: 'Ouzbekistan'},
  {code: 'PK', name: 'Pakistan'},
  {code: 'PS', name: 'Palestine'},
  {code: 'PA', name: 'Panama'},
  {code: 'PG', name: 'Papouasie-Nouvelle-Guinee'},
  {code: 'PY', name: 'Paraguay'},
  {code: 'NL', name: 'Pays-Bas'},
  {code: 'PE', name: 'Perou'},
  {code: 'PH', name: 'Philippines'},
  {code: 'PL', name: 'Pologne'},
  {code: 'PT', name: 'Portugal'},
  {code: 'QA', name: 'Qatar'},
  {code: 'RO', name: 'Roumanie'},
  {code: 'GB', name: 'Royaume-Uni'},
  {code: 'RU', name: 'Russie'},
  {code: 'RW', name: 'Rwanda'},
  {code: 'SN', name: 'Senegal'},
  {code: 'RS', name: 'Serbie'},
  {code: 'SL', name: 'Sierra Leone'},
  {code: 'SG', name: 'Singapour'},
  {code: 'SK', name: 'Slovaquie'},
  {code: 'SI', name: 'Slovenie'},
  {code: 'SO', name: 'Somalie'},
  {code: 'SD', name: 'Soudan'},
  {code: 'SS', name: 'Soudan du Sud'},
  {code: 'LK', name: 'Sri Lanka'},
  {code: 'SE', name: 'Suede'},
  {code: 'CH', name: 'Suisse'},
  {code: 'SR', name: 'Suriname'},
  {code: 'SY', name: 'Syrie'},
  {code: 'TJ', name: 'Tadjikistan'},
  {code: 'TZ', name: 'Tanzanie'},
  {code: 'TD', name: 'Tchad'},
  {code: 'CZ', name: 'Tchequie'},
  {code: 'TH', name: 'Thailande'},
  {code: 'TL', name: 'Timor oriental'},
  {code: 'TG', name: 'Togo'},
  {code: 'TN', name: 'Tunisie'},
  {code: 'TM', name: 'Turkmenistan'},
  {code: 'TR', name: 'Turquie'},
  {code: 'UA', name: 'Ukraine'},
  {code: 'UY', name: 'Uruguay'},
  {code: 'VE', name: 'Venezuela'},
  {code: 'VN', name: 'Vietnam'},
  {code: 'YE', name: 'Yemen'},
  {code: 'ZM', name: 'Zambie'},
  {code: 'ZW', name: 'Zimbabwe'},
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}

export function getCountryName(code: string): string {
  return getCountryByCode(code)?.name || code;
}

export function searchCountries(query: string): Country[] {
  if (!query.trim()) return COUNTRIES;
  const q = query.toLowerCase().trim();
  return COUNTRIES.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.code.toLowerCase().includes(q)
  );
}
